// <auto-generated />
#nullable enable
using System;
using System.ComponentModel;
using System.Linq;

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Contains the <see cref="AddServices(IServiceCollection)"/> extension methods to register 
    /// compile-time discovered services to an <see cref="IServiceCollection"/>.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    static partial class AddServicesNoReflectionExtension
    {
        static readonly ServiceDescriptor servicesAddedDescriptor = new ServiceDescriptor(typeof(DDIAddServicesAttribute), _ => new DDIAddServicesAttribute(), ServiceLifetime.Singleton);

        /// <summary>
        /// Adds the services that are assignable to <paramref name="assignableTo"/> to the collection, 
        /// in addition to the discovered services that were annotated with a <see cref="ServiceAttribute"/>.
        /// </summary>
        /// <remarks>
        /// Note that NO runtime reflection is performed when using this method. A compile-time source 
        /// generator will emit the relevant registration methods for all matching types (in the current 
        /// assembly or any referenced assemblies) at build time, resulting in maximum startup performance 
        /// as well as AOT-safety.
        /// </remarks>
        /// <param name="services">The <see cref="IServiceCollection"/> to add the services to.</param>
        /// <param name="assignableTo">The type that services must be assignable to in order to be registered.</param>
        /// <param name="lifetime">The service lifetime to register.</param>
        /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
        [DDIAddServices]
        public static IServiceCollection AddServices(this IServiceCollection services, Type assignableTo, ServiceLifetime lifetime = ServiceLifetime.Singleton) => services.AddServices();

        /// <summary>
        /// Adds the services that are assignable to <paramref name="assignableTo"/> to the collection, 
        /// in addition to the discovered services that were annotated with a <see cref="ServiceAttribute"/>.
        /// </summary>
        /// <remarks>
        /// Note that NO runtime reflection is performed when using this method. A compile-time source 
        /// generator will emit the relevant registration methods for all matching types (in the current 
        /// assembly or any referenced assemblies) at build time, resulting in maximum startup performance 
        /// as well as AOT-safety.
        /// </remarks>
        /// <param name="services">The <see cref="IServiceCollection"/> to add the services to.</param>
        /// <param name="fullNameExpression">Regular expression to match against the full name of the type to determine if it should be registered as a service.</param>
        /// <param name="lifetime">The service lifetime to register.</param>
        /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
        [DDIAddServices]
        public static IServiceCollection AddServices(this IServiceCollection services, string fullNameExpression, ServiceLifetime lifetime = ServiceLifetime.Singleton) => services.AddServices();

        /// <summary>
        /// Adds the services that are assignable to <paramref name="assignableTo"/> to the collection, 
        /// in addition to the discovered services that were annotated with a <see cref="ServiceAttribute"/>.
        /// </summary>
        /// <remarks>
        /// Note that NO runtime reflection is performed when using this method. A compile-time source 
        /// generator will emit the relevant registration methods for all matching types (in the current 
        /// assembly or any referenced assemblies) at build time, resulting in maximum startup performance 
        /// as well as AOT-safety.
        /// </remarks>
        /// <param name="services">The <see cref="IServiceCollection"/> to add the services to.</param>
        /// <param name="assignableTo">The type that services must be assignable to in order to be registered.</param>
        /// <param name="fullNameExpression">Regular expression to match against the full name of the type to determine if it should be registered as a service, in addition to being assignable to <paramref name="assignableTo"/>.</param>
        /// <param name="lifetime">The service lifetime to register.</param>
        /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
        [DDIAddServices]
        public static IServiceCollection AddServices(this IServiceCollection services, Type assignableTo, string fullNameExpression, ServiceLifetime lifetime = ServiceLifetime.Singleton) => services.AddServices();

        /// <summary>
        /// Adds the automatically discovered services that were annotated with a <see cref="ServiceAttribute"/>.
        /// </summary>
        /// <param name="services">The <see cref="IServiceCollection"/> to add the services to.</param>
        /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
        [DDIAddServices]
        public static IServiceCollection AddServices(this IServiceCollection services)
        {
            if (services.Contains(servicesAddedDescriptor))
                return services;

            AddScopedServices(services);
            AddSingletonServices(services);
            AddTransientServices(services);

            AddKeyedScopedServices(services);
            AddKeyedSingletonServices(services);
            AddKeyedTransientServices(services);

            services.Add(servicesAddedDescriptor);

            return services;
        }

        /// <summary>
        /// Decorates registrations for <typeparamref name="TDecorated"/> with <typeparamref name="TDecorator"/>.
        /// </summary>
        /// <remarks>
        /// The decorated service must already be registered before this method is invoked. The generated
        /// implementation replaces matching registrations in-place and preserves each registration lifetime.
        /// </remarks>
        /// <typeparam name="TDecorated">The service type to decorate.</typeparam>
        /// <typeparam name="TDecorator">The decorator type. It must implement <typeparamref name="TDecorated"/>.</typeparam>
        /// <param name="services">The <see cref="IServiceCollection"/> to update.</param>
        /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
        [DDIDecorate]
        public static IServiceCollection Decorate<TDecorated, TDecorator>(this IServiceCollection services)
            where TDecorated : class
            where TDecorator : class, TDecorated
        {
            DecorateServices<TDecorated, TDecorator>(services);
            return services;
        }

        /// <summary>
        /// Decorates keyed registrations for <typeparamref name="TDecorated"/> with <typeparamref name="TDecorator"/>.
        /// </summary>
        /// <remarks>
        /// The decorated service must already be registered with <paramref name="key"/> before this method is invoked.
        /// The generated implementation replaces matching registrations in-place and preserves each registration lifetime.
        /// </remarks>
        /// <typeparam name="TDecorated">The service type to decorate.</typeparam>
        /// <typeparam name="TDecorator">The decorator type. It must implement <typeparamref name="TDecorated"/>.</typeparam>
        /// <param name="services">The <see cref="IServiceCollection"/> to update.</param>
        /// <param name="key">The key for the service registration to decorate.</param>
        /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
        [DDIDecorate]
        public static IServiceCollection Decorate<TDecorated, TDecorator>(this IServiceCollection services, object? key)
            where TDecorated : class
            where TDecorator : class, TDecorated
        {
            DecorateKeyedServices<TDecorated, TDecorator>(services, key);
            return services;
        }

        /// <summary>
        /// Adds discovered scoped services to the collection.
        /// </summary>
        static partial void AddScopedServices(IServiceCollection services);

        /// <summary>
        /// Adds discovered singleton services to the collection.
        /// </summary>
        static partial void AddSingletonServices(IServiceCollection services);

        /// <summary>
        /// Adds discovered transient services to the collection.
        /// </summary>
        static partial void AddTransientServices(IServiceCollection services);

        /// <summary>
        /// Adds discovered keyed scoped services to the collection.
        /// </summary>
        static partial void AddKeyedScopedServices(IServiceCollection services);

        /// <summary>
        /// Adds discovered keyed singleton services to the collection.
        /// </summary>
        static partial void AddKeyedSingletonServices(IServiceCollection services);

        /// <summary>
        /// Adds discovered keyed transient services to the collection.
        /// </summary>
        static partial void AddKeyedTransientServices(IServiceCollection services);

        /// <summary>
        /// Applies source-generated service decorations.
        /// </summary>
        static partial void DecorateServices<TDecorated, TDecorator>(IServiceCollection services)
            where TDecorated : class
            where TDecorator : class, TDecorated;

        /// <summary>
        /// Applies source-generated keyed service decorations.
        /// </summary>
        static partial void DecorateKeyedServices<TDecorated, TDecorator>(IServiceCollection services, object? key)
            where TDecorated : class
            where TDecorator : class, TDecorated;

        static void DecorateDescriptors<TDecorated, TDecorator>(
            IServiceCollection services,
            Func<IServiceProvider, ServiceDescriptor, TDecorated> factory)
            where TDecorated : class
            where TDecorator : class, TDecorated
        {
            DecorateDescriptors<TDecorated, TDecorator>(services, null, (sp, _, sd) => factory(sp, sd));
        }

        static void DecorateDescriptors<TDecorated, TDecorator>(
            IServiceCollection services,
            object? key,
            Func<IServiceProvider, object?, ServiceDescriptor, TDecorated> factory)
            where TDecorated : class
            where TDecorator : class, TDecorated
        {
            bool isKeyed = key is not null;

            var descriptors = services
                .Select((descriptor, index) => new { descriptor, index })
                .Where(x =>
                    x.descriptor.IsKeyedService == isKeyed &&
                    x.descriptor.ServiceType == typeof(TDecorated) &&
                    (!isKeyed || Equals(x.descriptor.ServiceKey, key)) &&
                    GetImplementationType(x.descriptor) != typeof(TDecorator))
                .ToArray();

            if (descriptors.Length == 0)
            {
                throw new InvalidOperationException(isKeyed
                    ? $"No keyed service registration for {typeof(TDecorated)} with key '{key}' was found. Call AddServices before Decorate, or register the decorated service before decorating it."
                    : $"No service registration for {typeof(TDecorated)} was found. Call AddServices before Decorate, or register the decorated service before decorating it.");
            }

            foreach (var item in descriptors)
            {
                if (!isKeyed)
                {
                    services[item.index] = ServiceDescriptor.Describe(
                        typeof(TDecorated),
                        provider => factory(provider, null, item.descriptor),
                        item.descriptor.Lifetime);
                }
                else
                {
                    services[item.index] = ServiceDescriptor.DescribeKeyed(
                        typeof(TDecorated),
                        key,
                        (provider, serviceKey) => factory(provider, serviceKey, item.descriptor),
                        item.descriptor.Lifetime);
                }
            }
        }



        static TDecorated GetDecorated<TDecorated>(IServiceProvider provider, ServiceDescriptor descriptor)
            where TDecorated : class
            => GetDecoratedCore<TDecorated>(provider, null, descriptor);

        static TDecorated GetKeyedDecorated<TDecorated>(IServiceProvider provider, object? key, ServiceDescriptor descriptor)
            where TDecorated : class
            => GetDecoratedCore<TDecorated>(provider, key, descriptor);

        static TDecorated GetDecoratedCore<TDecorated>(IServiceProvider provider, object? key, ServiceDescriptor descriptor)
            where TDecorated : class
        {
            bool isKeyed = key is not null;

            if (isKeyed)
            {
                if (!descriptor.IsKeyedService)
                    throw new InvalidOperationException($"Non-keyed service registrations for {typeof(TDecorated)} cannot be decorated by this overload.");
            }
            else
            {
                if (descriptor.IsKeyedService)
                    throw new InvalidOperationException($"Keyed service registrations for {typeof(TDecorated)} cannot be decorated by this overload.");
            }

            object? service;

            if (descriptor.IsKeyedService)
            {
                if (descriptor.KeyedImplementationInstance != null)
                {
                    service = descriptor.KeyedImplementationInstance;
                }
                else if (descriptor.KeyedImplementationFactory != null)
                {
                    service = descriptor.KeyedImplementationFactory(provider, key);
                }
                else if (descriptor.KeyedImplementationType != null)
                {
                    service = ActivatorUtilities.GetServiceOrCreateInstance(provider, descriptor.KeyedImplementationType);
                }
                else
                {
                    throw new InvalidOperationException($"Unsupported keyed service registration for {typeof(TDecorated)}.");
                }
            }
            else
            {
                if (descriptor.ImplementationInstance != null)
                {
                    service = descriptor.ImplementationInstance;
                }
                else if (descriptor.ImplementationFactory != null)
                {
                    service = descriptor.ImplementationFactory(provider);
                }
                else if (descriptor.ImplementationType != null)
                {
                    service = ActivatorUtilities.GetServiceOrCreateInstance(provider, descriptor.ImplementationType);
                }
                else
                {
                    throw new InvalidOperationException($"Unsupported service registration for {typeof(TDecorated)}.");
                }
            }

            return service as TDecorated ??
                throw new InvalidOperationException($"The decorated registration did not produce an instance of {typeof(TDecorated)}.");
        }

        static Type? GetImplementationType(ServiceDescriptor descriptor)
        {
            if (descriptor.IsKeyedService)
                return descriptor.KeyedImplementationType;

            return descriptor.ImplementationType ?? descriptor.ImplementationInstance?.GetType();
        }

        [AttributeUsage(AttributeTargets.Method)]
        class DDIAddServicesAttribute : Attribute { }

        [AttributeUsage(AttributeTargets.Method)]
        class DDIDecorateAttribute : Attribute { }
    }
}