// <auto-generated />
using System;

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Configures the registration of a service in an <see cref="IServiceCollection"/> using 
    /// a specific service type.
    /// </summary>
    /// <remarks>
    /// Registers the service using the specific service interface, 
    /// as well as <c>Func&lt;TService&gt;</c> and <c>Lazy&lt;TService&gt;</c>, 
    /// so the instance can be lazily retrieved.
    /// </remarks>
    /// <typeparam name="TService">Type of service to register.</typeparam>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    partial class ServiceAttribute<TService> : Attribute
    {
        /// <summary>
        /// Annotates the service with the lifetime.
        /// </summary>
        public ServiceAttribute(ServiceLifetime lifetime = ServiceLifetime.Singleton) { }

        /// <summary>
        /// Annotates the service with the given key and lifetime.
        /// </summary>
        public ServiceAttribute(object key, ServiceLifetime lifetime = ServiceLifetime.Singleton) { }
    }
}