// <auto-generated />
#nullable enable
using System;

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Configures the registration of a service in an <see cref="IServiceCollection"/>.
    /// </summary>
    /// <remarks>
    /// Registers the service using all interfaces implemented by the target, 
    /// as well as <c>Func{TInterface}</c> and <c>Lazy{TInterface}</c> for each, 
    /// so the instance can be lazily retrieved.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    partial class ServiceAttribute : Attribute
    {
        /// <summary>
        /// Annotates the service with the lifetime.
        /// </summary>
        public ServiceAttribute(ServiceLifetime lifetime = ServiceLifetime.Singleton) { }

        /// <summary>
        /// Annotates the service with the given key and lifetime.
        /// </summary>
        public ServiceAttribute(object key, ServiceLifetime lifetime = ServiceLifetime.Singleton) { }
    }
}